image:
  file: Dockerfile

tasks:
  - command : >
        cp catalina.properties /opt/tomcat/conf &&
        cp connection.properties /opt/tomcat/conf &&
        cp webMAP.properties /opt/tomcat/conf/webMap.properties &&
        cp ReferenceApplication/target/ws-1.0.0.war /opt/tomcat/webapps/ROOT.war &&
        /opt/tomcat/bin/catalina.sh start

ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - florianbaer.pb-syntax@0.2.1:8BpBR6gFIBo7WD55piDsXw==
